---
pagetitle: "Soohun Kim | Research"
---

<link rel="stylesheet" href="styles.css" type="text/css">


# Published and Accepted Papers

* **Analyzing Active Fund Managers' Commitment to ESG: Evidence from the United Nations Principles for Responsible Investment**  
with 
[Aaron Yoon](https://www.kellogg.northwestern.edu/faculty/directory/yoon_aaron.aspx) 
__Management Science__, (2023), 69, 723-1322.  
[[MS]](https://pubsonline.informs.org/doi/abs/10.1287/mnsc.2022.4394?journalCode=mnsc)


* **Revealed Heuristics: Evidence from Investment Consultants’ Search Behavior**  
with 
[Sudheer Chava](https://www.scheller.gatech.edu/directory/faculty/chava/index.html)  and
[Daniel Weagley](https://www.danielweagley.com/)
__Review of Asset Pricing Studies__, (2022), 12, 543-592.  
[[RAPS]](https://academic.oup.com/raps/article-abstract/12/2/543/6446040?redirectedFrom=fulltext)


* **Characteristic-Based Returns: Alpha or Smart Beta?**  
with  [Robert Korajczyk](https://www.kellogg.northwestern.edu/faculty/directory/korajczyk_robert.aspx)  and
[Andy Neuhierl](https://olin.wustl.edu/EN-US/Faculty-Research/Faculty/Pages/FacultyDetail.aspx?username=andreasn)
__Journal of Investment Management__, (2022), 20, 70-89.  
[[JOIM]](https://joim.com/characteristic-based-returns-alpha-or-smart-beta/)


* **Arbitrage Portfolios**  
with  [Robert Korajczyk](https://www.kellogg.northwestern.edu/faculty/directory/korajczyk_robert.aspx)  and
[Andy Neuhierl](https://olin.wustl.edu/EN-US/Faculty-Research/Faculty/Pages/FacultyDetail.aspx?username=andreasn)
__Review of Financial Studies__, (2021), 34, 2813–2856.  
[[RFS]](https://academic.oup.com/rfs/article/34/6/2813/5902462)

* **Self-fulfilling arbitrages necessitate crash risk**  
with 
[Donghyun Ahn](https://econ.snu.ac.kr/people/faculty?mode=view&profidx=14) and 
[Kyoungwon Seo](https://sites.google.com/view/kyoungwon-seo)
__Journal of Financial Markets__,  (2020), 51, 100547.  
[[JFM]](https://www.sciencedirect.com/science/article/pii/S1386418120300161)

* **Ex-post risk premia estimation and asset pricing tests using large cross sections: The regression-calibration approach**  
with 
[Georgios Skoulakis](https://sites.google.com/view/geskoulakis/home) 
__Journal of Econometrics__,  (2018), 204, 159-188.  
[[JOE]](https://www.sciencedirect.com/science/article/pii/S0304407618300198)


## Working Papers

* **Large Sample Estimators of Stochastic Discount Factor**  
with 
[Robert Korajczyk](https://www.kellogg.northwestern.edu/faculty/directory/korajczyk_robert.aspx)  
[[SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3131274)


* **Capital Allocation and the Market for Mutual Funds: Inspecting the Mechanism**  
with
[Jules van Binsbergen](https://sites.google.com/view/jules-van-binsbergen/)  and
[John Kim](https://sites.google.com/view/john-kim)  
[[SSRN]](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3462749)

 
